export default [
  {url: 'https://rpc.hydradx.cloud', name: 'GC', location: '?'},
  {url: 'https://hydration-rpc.n.dwellir.com', name: 'Dwellir', location: '?'},
  {url: 'https://rpc.helikon.io/hydradx', name: 'Helicon', location: '?'},
  {url: 'https://hydration.dotters.network', name: 'Dotters', location: '?'},
  {url: 'https://hydration.ibp.network', name: 'IBP', location: '?'},
  {url: 'https://rpc.cay.hydration.cloud', name: 'cay', location: 'TR'},
  {url: 'https://rpc.parm.hydration.cloud', name: 'parm', location: 'DE'},
  {url: 'https://rpc.roach.hydration.cloud', name: 'roach', location: 'PL'},
  {url: 'https://rpc.zipp.hydration.cloud', name: 'zipp', location: 'FR'},
  {url: 'https://archive.rpc.hydration.cloud', name: 'Archive', location: '?'},
  {url: 'https://rpc.sin.hydration.cloud', name: 'sin', location: 'SG'},
  {url: 'https://rpc.coke.hydration.cloud', name: 'coke', location: 'SG'},
  {url: 'https://rpc.lait.hydration.cloud', name: 'lait', location: 'FR'},
  {url: 'https://rpc.limo.hydration.cloud', name: 'limo', location: 'PL'},
  {url: 'https://5.rpc.hydration.cloud', name: '5', location: 'DE'},
  {url: 'https://4.rpc.hydration.cloud', name: '4', location: 'CA'},
  {url: 'https://7.rpc.hydration.cloud', name: '7', location: 'CA'},
  {url: 'https://3.rpc.hydration.cloud', name: '3', location: 'UK'},
]
