export default [
  { url: 'https://rpc.hydradx.cloud', name: 'GC', location: '?' },
  {
    url: 'https://hydration-rpc.n.dwellir.com',
    name: 'Dwellir',
    location: '?',
  },
  { url: 'https://rpc.helikon.io/hydradx', name: 'Helicon', location: '?' },
  { url: 'https://hydration.dotters.network', name: 'Dotters', location: '?' },
  { url: 'https://hydration.ibp.network', name: 'IBP', location: '?' },
  { url: 'https://node.parm.hydration.cloud', name: 'parm', location: 'DE' },
  { url: 'https://rpc.roach.hydration.cloud', name: 'roach', location: 'PL' },
  { url: 'https://rpc.zipp.hydration.cloud', name: 'zipp', location: 'FR' },
  { url: 'https://rpc.sin.hydration.cloud', name: 'sin', location: 'SG' },
  { url: 'https://rpc.coke.hydration.cloud', name: 'coke', location: 'SG' },
  { url: 'https://rpc.lait.hydration.cloud', name: 'lait', location: 'FR' },
  { url: 'https://hydration.rpc.stkd.io', name: 'stkd', location: 'BR' },
  { url: 'https://node-catfish-1.catfish.hydration.cloud', name: 'catfish1', location: '?' },
  { url: 'https://node-catfish-2.catfish.hydration.cloud', name: 'catfish2', location: '?' },
  { url: 'https://node-catfish-3.catfish.hydration.cloud', name: 'catfish3', location: '?' },
  { url: 'https://node-catfish-4.catfish.hydration.cloud', name: 'catfish4', location: '?' },
  { url: 'https://node-catfish-5.catfish.hydration.cloud', name: 'catfish5', location: '?' },
  { url: 'https://node-dir.kril.hydration.cloud', name: 'kril', location: '?' },
  { url: 'https://hdx.tarn.hydration.cloud', name: 'tarn', location: '?' },
  { url: 'https://node.lark.hydration.cloud', name: 'lark1', location: '?', testnet: true },
  { url: 'https://node2.lark.hydration.cloud', name: 'lark2', location: '?', testnet: true },
  { url: 'https://node3.lark.hydration.cloud', name: 'lark3', location: '?', testnet: true },
  { url: 'https://node4.lark.hydration.cloud', name: 'lark4', location: '?', testnet: true },
  { url: 'https://node5.lark.hydration.cloud', name: 'lark5', location: '?', testnet: true },
  { url: 'https://paseo-rpc.play.hydration.cloud', name: 'paseo', location: '?', testnet: true },
];
